In [1]:
import sklearn

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from sklearn import preprocessing

In [7]:
from sklearn.ensemble import RandomForestRegressor

In [8]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV

In [9]:
from sklearn.metrics import mean_squared_error,r2_score

In [11]:
import joblib

In [16]:
#dataset_url='http://mlr.cs.umass.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
#data=pd.read_csv(dataset_url,sep=';')
data=pd.read_csv('winequality-red.csv',sep=';')

In [18]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [20]:
data.shape

(1599, 12)

In [21]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [24]:
y=data['quality']
X=data.drop('quality',axis=1)

In [40]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=123,stratify=y)

In [41]:
X_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
691             9.2              0.92         0.24             2.6      0.087   
1475            5.3              0.47         0.11             2.2      0.048   
1065            7.7              0.61         0.18             2.4      0.083   
1159           10.2              0.41         0.43             2.2      0.110   
227             9.0              0.82         0.14             2.6      0.089   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
691                  12.0                  93.0  0.99980  3.48       0.54   
1475                 16.0                  89.0  0.99182  3.54       0.88   
1065                  6.0                  20.0  0.99630  3.29       0.60   
1159                 11.0                  37.0  0.99728  3.16       0.67   
227                   9.0                  23.0  0.99840  3.39       0.63   

        alcohol  
691    9.800000  
1475  13.566667  
1065  10.200000  
1159  10.800000  
227    9.800000

In [42]:
X_test.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
797             9.3             0.370         0.44             1.6      0.038   
871             6.9             0.560         0.03             1.5      0.086   
1333            9.1             0.775         0.22             2.2      0.079   
1463            6.9             0.630         0.01             2.4      0.076   
1058            9.9             0.530         0.57             2.4      0.093   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
797                  21.0                  42.0  0.99526  3.24       0.81   
871                  36.0                  46.0  0.99522  3.53       0.57   
1333                 12.0                  48.0  0.99760  3.18       0.51   
1463                 14.0                  39.0  0.99522  3.34       0.53   
1058                 30.0                  52.0  0.99710  3.19       0.76   

      alcohol  
797      10.8  
871      10.6  
1333      9.6  
1463     10.8  
1058     11.6

In [43]:
y_train.head()

691     5
1475    7
1065    6
1159    5
227     5
Name: quality, dtype: int64

In [44]:
y_test.head()

797     7
871     5
1333    5
1463    6
1058    7
Name: quality, dtype: int64

In [45]:
scaler= preprocessing.StandardScaler().fit(X_train)

In [46]:
X_tX_train_scaled11rain_scaled=scaler.transform(X_train)

In [49]:
X_train_scaled.mean(axis=0)

array([ 1.16664562e-16, -3.05550043e-17, -8.47206937e-17, -2.22218213e-17,
        2.22218213e-17, -6.38877362e-17, -4.16659149e-18, -2.54439854e-15,
       -8.70817622e-16, -4.08325966e-16, -1.17220107e-15])

In [50]:
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
X_test_scaled=scaler.transform(X_test)

In [52]:
X_test_scaled.mean(axis=0)

array([ 0.02776704,  0.02592492, -0.03078587, -0.03137977, -0.00471876,
       -0.04413827, -0.02414174, -0.00293273, -0.00467444, -0.10894663,
        0.01043391])

In [54]:
X_test_scaled.std(axis=0)

array([1.02160495, 1.00135689, 0.97456598, 0.91099054, 0.86716698,
       0.94193125, 1.03673213, 1.03145119, 0.95734849, 0.83829505,
       1.0286218 ])

In [58]:
pipeline=make_pipeline(preprocessing.StandardScaler(),RandomForestRegressor(n_estimators=100))

In [59]:
pipeline.get_params()

{'memory': None,
 'steps': [('standardscaler',
   StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('randomforestregressor',
   RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                         max_features='auto', max_leaf_nodes=None,
                         min_impurity_decrease=0.0, min_impurity_split=None,
                         min_samples_leaf=1, min_samples_split=2,
                         min_weight_fraction_leaf=0.0, n_estimators=100,
                         n_jobs=None, oob_score=False, random_state=None,
                         verbose=0, warm_start=False))],
 'verbose': False,
 'standardscaler': StandardScaler(copy=True, with_mean=True, with_std=True),
 'randomforestregressor': RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                       max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1,

In [63]:
hyperparameters={'randomforestregressor__max_features': ['auto','sqrt','log2'],'randomforestregressor__max_depth': [None, 5, 3, 1]}

In [64]:
hyperparameters

{'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'],
 'randomforestregressor__max_depth': [None, 5, 3, 1]}

In [65]:
clf=GridSearchCV(pipeline,hyperparameters,cv=10)
#fit and tune model
clf.fit(X_train,y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('randomforestregressor',
                                        RandomForestRegressor(bootstrap=True,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              min_impurity_decrease=0.0,
                                                              min_impurity_split

In [66]:
clf.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'log2'}

In [67]:
clf.refit

True

In [68]:
y_pred=clf.predict(X_test)

In [70]:
r2_score(y_test,y_pred)

0.4782691446213453

In [71]:
mean_squared_error(y_test,y_pred)

0.3366590625

In [72]:
joblib.dump(clf,'rf_regressor.plk')
#load model from plk file
#clf2=joblib.load('rf_regressor.pkl')
# Predict data set using loaded model
#clf2.predict(X_test)

['rf_regressor.plk']